/* +++ begin copyright +++ ********************************************/
/*                                                                    */
/* Copyright (c) 1994-2001.                                           */
/* Cisco Systems, Inc.                                                */
/* All rights reserved.                                               */
/*                                                                    */
/* Confidential restricted material.  This work contains confidential */
/* trade secrets of Cisco Systems, Inc.  Use, examination, copying,   */
/* transfer and/or disclosure to others are prohibited, except with   */
/* the express written agreement of Cisco Systems, Inc.               */
/*                                                                    */
/* +++ end copyright +++ **********************************************/

// 
// 	CTILink.h
//
// 	This file defines the symbolic constants and definitions of
//	Cisco Systems CTIServer Interface.
//
//	$Revision: 4 $
//	$Modtime: 4/05/01 5:54p $
//


#ifndef __CTILINK_H__
#define __CTILINK_H__

#ifdef __cplusplus
#	define BEGIN_ENUM( x )	 enum x {
#	define END_ENUM( x )	};
#else
#	define BEGIN_ENUM( x ) typedef enum tag ## x {
#	define END_ENUM( x )	} x;
 #endif


//	Symbolic Constants

#define	CTILINK_VERSION_2				2	/* version 2 ICM 2.0 */
#define	CTILINK_VERSION_3				3	/* version 3 ICM 2.5 */
#define CTILINK_VERSION_5				5   /* version 5 ICM 3.0 */
#define CTILINK_VERSION_6				6	/* version 6 ICM 4.1 Enterprise Agent and Expanded Call Context enhancements */
#define CTILINK_VERSION_7				7	/* version 7 ICM 4.5 Reporting + etc */
#define CTILINK_VERSION_8				8	/* version 8 ICM 4.6 Supervisor services message and Blended Agent */
#define CTILINK_VERSION_12				12	/* version 12 ICM 7.0 Supervisor services message and Blended Agent */

#define	CTILINK_VERSION					CTILINK_VERSION_12			/* most recent version */

#define	MAX_CTILINK_MSG_LENGTH_V2		2061 /* version 2 (ICM 2.0) */
#define	MAX_CTILINK_MSG_LENGTH_V3		4329 /* version 3 (ICM 2.5) */
#define	MAX_CTILINK_MSG_LENGTH_V6		6843 /* version 6 (ICM 4.1) */
#define	MAX_CTILINK_MSG_LENGTH_V7		6843 /* version 7 (ICM 4.5) */
#define	MAX_CTILINK_MSG_LENGTH_V8		6843 /* version 8 (ICM 4.6) */

#define	MAX_CTILINK_MSG_LENGTH			MAX_CTILINK_MSG_LENGTH_V8	/* most recent version */

#define	NUM_CALL_VARIABLES				10

#define	MAX_NUM_CTI_CLIENTS				16
#define	MAX_NUM_PARTIES					16
#define	MAX_NUM_DEVICES					16
#define	MAX_NUM_CALLS					16
#define	MAX_NUM_SKILL_GROUPS_V3			10
#define	MAX_NUM_SKILL_GROUPS_V5			20
#define	MAX_NUM_SKILL_GROUPS			MAX_NUM_SKILL_GROUPS_V5		/* most recent version */
#define	MAX_NUM_LINES					10
#define	MAX_NUM_AGENTS					64
#define	MAX_NUM_AGENT_TEAMS				64
#define	MAX_NUM_SUPERVISORS				64

#define	MAX_CLIENT_ADDR_LENGTH			16
#define	MAX_CLIENT_ID_LENGTH			64
#define	MAX_CLIENT_PASSWORD_LENGTH		32
#define	MAX_AGENT_EXTENSION_LENGTH		16
#define	MAX_AGENT_ID_LENGTH				12
#define	MAX_AGENT_INSTRUMENT_LENGTH_V1	12
#define	MAX_AGENT_INSTRUMENT_LENGTH_V6	64
#define	MAX_AGENT_INSTRUMENT_LENGTH		MAX_AGENT_INSTRUMENT_LENGTH_V6
#define	MAX_AGENT_PASSWORD_LENGTH		32
#define	MAX_ANI_LENGTH					40
#define	MAX_USER_TO_USER_LENGTH			131
#define	MAX_DNIS_LENGTH					32
#define	MAX_DIALED_NUMBER_LENGTH		40
#define	MAX_CALLER_ENTERED_DIGITS_LENGTH	40
#define	MAX_CALL_VARIABLE_LENGTH		40
#define	MAX_DEVICE_ID_LENGTH			64
#define	MAX_CALL_WRAPUP_DATA_LENGTH		40
#define	MAX_TEXT_LENGTH					255
#define	MAX_OBJECT_NAME_LENGTH			128
#define	MAX_FACILITY_CODE_LENGTH		40
#define	MAX_DTMF_STRING_LENGTH			32
#define	MAX_QUERY_DEVICE_DATA_LENGTH	892
#define	MAX_AUTHORIZATION_CODE_LENGTH	40
#define	MAX_ACCOUNT_CODE_LENGTH			40
#define MAX_LINE_ID_LENGTH				40
#define	MAX_VAR_NAME_LENGTH				33
#define MAX_VAR_VALUE_LENGTH			211
#define MAX_BINDATA_SIZE				2000
#define MAX_VAR_ARRAY_SIZE				255
#define	MAX_SUPERVISOR_INSTRUMENT_LENGTH MAX_AGENT_INSTRUMENT_LENGTH
#define	MAX_DEVICE_PORT_ADDRESS_LENGTH	32
#define MAX_SERVICE_NAME_LENGTH			64

#define	MIN_CTILINK_HEARTBEAT_INTERVAL	5

//	Special Values

#define	NO_TIMEOUT			0xffffffff
#define	NULL_CALL_ID		0xffffffff
#define	NULL_PERIPHERAL_ID	0xffffffff
#define	NULL_SERVICE		0xffffffff
#define	NULL_SKILL_GROUP	0xffffffff
#define NULL_CALLTYPE		0xffff

//	CTILink Message Types

BEGIN_ENUM(CTILinkMsgType)
	NULL_MSG						= 0,
	FAILURE_CONF					= 1,
	FAILURE_EVENT					= 2,
	OPEN_REQ						= 3,
	OPEN_CONF						= 4,
	HEARTBEAT_REQ					= 5,
	HEARTBEAT_CONF					= 6,
	CLOSE_REQ						= 7,
	CLOSE_CONF						= 8,
	CALL_DELIVERED_EVENT			= 9,
	CALL_ESTABLISHED_EVENT			= 10,
	CALL_HELD_EVENT					= 11,
	CALL_RETRIEVED_EVENT			= 12,
	CALL_CLEARED_EVENT				= 13,
	CALL_CONNECTION_CLEARED_EVENT	= 14,
	CALL_ORIGINATED_EVENT			= 15,
	CALL_FAILED_EVENT				= 16,
	CALL_CONFERENCED_EVENT			= 17,
	CALL_TRANSFERRED_EVENT			= 18,
	CALL_DIVERTED_EVENT				= 19,
	CALL_SERVICE_INITIATED_EVENT	= 20,
	CALL_QUEUED_EVENT				= 21,
	CALL_TRANSLATION_ROUTE_EVENT	= 22,
	BEGIN_CALL_EVENT				= 23,
	END_CALL_EVENT					= 24,
	CALL_DATA_UPDATE_EVENT			= 25,
	SET_CALL_DATA_REQ				= 26,
	SET_CALL_DATA_CONF				= 27,
	RELEASE_CALL_REQ				= 28,
	RELEASE_CALL_CONF				= 29,
	AGENT_STATE_EVENT				= 30,
	SYSTEM_EVENT					= 31,

	LAST_CTI_MSG_TYPE_V2			= SYSTEM_EVENT,	/* version 2 ICM 2.0 */

	CLIENT_EVENT_REPORT_REQ			= 32,
	CLIENT_EVENT_REPORT_CONF		= 33,
	CALL_REACHED_NETWORK_EVENT		= 34,
	CONTROL_FAILURE_CONF			= 35,
	QUERY_AGENT_STATE_REQ			= 36,
	QUERY_AGENT_STATE_CONF			= 37,
	SET_AGENT_STATE_REQ				= 38,
	SET_AGENT_STATE_CONF			= 39,
	ALTERNATE_CALL_REQ				= 40,
	ALTERNATE_CALL_CONF				= 41,
	ANSWER_CALL_REQ					= 42,
	ANSWER_CALL_CONF				= 43,
	CLEAR_CALL_REQ					= 44,
	CLEAR_CALL_CONF					= 45,
	CLEAR_CONNECTION_REQ			= 46,
	CLEAR_CONNECTION_CONF			= 47,
	CONFERENCE_CALL_REQ				= 48,
	CONFERENCE_CALL_CONF			= 49,
	CONSULTATION_CALL_REQ			= 50,
	CONSULTATION_CALL_CONF			= 51,
	DEFLECT_CALL_REQ				= 52,
	DEFLECT_CALL_CONF				= 53,
	HOLD_CALL_REQ					= 54,
	HOLD_CALL_CONF					= 55,
	MAKE_CALL_REQ					= 56,
	MAKE_CALL_CONF					= 57,
	MAKE_PREDICTIVE_CALL_REQ		= 58,
	MAKE_PREDICTIVE_CALL_CONF		= 59,
	RECONNECT_CALL_REQ				= 60,
	RECONNECT_CALL_CONF				= 61,
	RETRIEVE_CALL_REQ				= 62,
	RETRIEVE_CALL_CONF				= 63,
	TRANSFER_CALL_REQ				= 64,
	TRANSFER_CALL_CONF				= 65,
	QUERY_MSG_WAITING_IND_REQ		= 66,
	QUERY_MSG_WAITING_IND_CONF		= 67,
	SET_MSG_WAITING_IND_REQ			= 68,
	SET_MSG_WAITING_IND_CONF		= 69,
	QUERY_DO_NOT_DISTURB_REQ		= 70,
	QUERY_DO_NOT_DISTURB_CONF		= 71,
	SET_DO_NOT_DISTURB_REQ			= 72,
	SET_DO_NOT_DISTURB_CONF			= 73,
	QUERY_FORWARDING_REQ			= 74,
	QUERY_FORWARDING_CONF			= 75,
	SET_FORWARDING_REQ				= 76,
	SET_FORWARDING_CONF				= 77,
	QUERY_DEVICE_INFO_REQ			= 78,
	QUERY_DEVICE_INFO_CONF			= 79,
	QUERY_LAST_NUMBER_DIALED_REQ	= 80,
	QUERY_LAST_NUMBER_DIALED_CONF	= 81,
	SNAPSHOT_CALL_REQ				= 82,
	SNAPSHOT_CALL_CONF				= 83,
	SNAPSHOT_DEVICE_REQ				= 84,
	SNAPSHOT_DEVICE_CONF			= 85,
	CALL_DEQUEUED_EVENT				= 86,
	QUERY_AGENT_WORK_MODE_REQ		= 87,
	QUERY_AGENT_WORK_MODE_CONF		= 88,
	SET_AGENT_WORK_MODE_REQ			= 89,
	SET_AGENT_WORK_MODE_CONF		= 90,
	SEND_DTMF_SIGNAL_REQ			= 91,
	SEND_DTMF_SIGNAL_CONF			= 92,

	LAST_CTI_MSG_TYPE_V3			= SEND_DTMF_SIGNAL_CONF,	/* CTI version 3, ICM 2.5 */

	MONITOR_START_REQ					= 93,
	MONITOR_START_CONF					= 94,
	MONITOR_STOP_REQ					= 95,
	MONITOR_STOP_CONF					= 96,
	CHANGE_MONITOR_MASK_REQ				= 97,
	CHANGE_MONITOR_MASK_CONF			= 98,
	CLIENT_SESSION_OPENED_EVENT			= 99,
	CLIENT_SESSION_CLOSED_EVENT			= 100,
	SESSION_MONITOR_START_REQ			= 101,
	SESSION_MONITOR_START_CONF			= 102,
	SESSION_MONITOR_STOP_REQ			= 103,
	SESSION_MONITOR_STOP_CONF			= 104,

	LAST_CTI_MSG_TYPE_V5			= SESSION_MONITOR_STOP_CONF,	/* CTI version 5, ICM 3.0 */

	AGENT_PRE_CALL_EVENT				= 105,
	AGENT_PRE_CALL_ABORT_EVENT			= 106,
	USER_MESSAGE_REQ					= 107,
	USER_MESSAGE_CONF					= 108,
	USER_MESSAGE_EVENT					= 109,
	REGISTER_VARIABLES_REQ				= 110,
	REGISTER_VARIABLES_CONF				= 111,
	QUERY_AGENT_STATISTICS_REQ			= 112,
	QUERY_AGENT_STATISTICS_CONF			= 113,
	QUERY_SKILL_GROUP_STATISTICS_REQ	= 114,
	QUERY_SKILL_GROUP_STATISTICS_CONF	= 115,

	LAST_CTI_MSG_TYPE_V6	= QUERY_SKILL_GROUP_STATISTICS_CONF,	/* CTI version 6, ICM 4. */

	RTP_STARTED_EVENT					= 116,
	RTP_STOPPED_EVENT					= 117,

	LAST_CTI_MSG_TYPE_V7	= RTP_STOPPED_EVENT,					/* CTI version 7, ICM 4.5 */

	SUPERVISOR_ASSIST_REQ				= 118,
	SUPERVISOR_ASSIST_CONF				= 119,
	SUPERVISOR_ASSIST_EVENT				= 120,
	EMERGENCY_CALL_REQ					= 121,
	EMERGENCY_CALL_CONF					= 122,
	EMERGENCY_CALL_EVENT				= 123,
	SUPERVISE_CALL_REQ					= 124,
	SUPERVISE_CALL_CONF					= 125,
	AGENT_TEAM_CONFIG_REQ				= 126,
	AGENT_TEAM_CONFIG_CONF				= 127,
	AGENT_TEAM_CONFIG_EVENT				= 128,
	SET_APP_DATA_REQ					= 129,
	SET_APP_DATA_CONF					= 130,
	AGENT_DESK_SETTINGS_REQ				= 131,
	AGENT_DESK_SETTINGS_CONF			= 132,
	LIST_AGENT_TEAM_REQ					= 133,
	LIST_AGENT_TEAM_CONF				= 134,
	MONITOR_AGENT_TEAM_START_REQ		= 135,
	MONITOR_AGENT_TEAM_START_CONF		= 136,
	MONITOR_AGENT_TEAM_STOP_REQ			= 137,
	MONITOR_AGENT_TEAM_STOP_CONF		= 138,
	BAD_CALL_REQ						= 139,
	BAD_CALL_CONF						= 140,
	SET_DEVICE_ATTRIBUTES_REQ			= 141,
	SET_DEVICE_ATTRIBUTES_CONF			= 142,
	REGISTER_SERVICE_REQ				= 143,
	REGISTER_SERVICE_CONF				= 144,
	UNREGISTER_SERVICE_REQ				= 145,
	UNREGISTER_SERVICE_CONF				= 146,
	START_RECORDING_REQ					= 147,
	START_RECORDING_CONF				= 148,
	STOP_RECORDING_REQ					= 149,
	STOP_RECORDING_CONF					= 150,

	LAST_CTI_MSG_TYPE_V8	= STOP_RECORDING_CONF,	/* CTI version 8, ICM 4.6 */

	LAST_CTI_MSG_TYPE	= LAST_CTI_MSG_TYPE_V8
END_ENUM(CTILinkMsgType)

//	Error status codes

BEGIN_ENUM(CTILinkStatusCode)
	E_CTI_NO_ERROR					    = 0,
	E_CTI_INVALID_VERSION			    = 1,
	E_CTI_INVALID_MESSAGE_LENGTH	    = 2,
	E_CTI_INVALID_FIELD_TAG			    = 3,
	E_CTI_SESSION_NOT_OPEN			    = 4,
	E_CTI_SESSION_ALREADY_OPEN		    = 5,
	E_CTI_REQUIRED_DATA_MISSING		    = 6,
	E_CTI_INVALID_PERIPHERAL_ID		    = 7,
	E_CTI_INVALID_AGENT_DATA		    = 8,
	E_CTI_AGENT_NOT_LOGGED_ON		    = 9,
	E_CTI_DEVICE_IN_USE				    = 10,
	E_CTI_NEW_SESSION_OPENED		    = 11,
	E_CTI_FUNCTION_NOT_AVAILABLE	    = 12,
	E_CTI_INVALID_CALLID			    = 13,
	E_CTI_PROTECTED_VARIABLE		    = 14,
	E_CTI_CTI_SERVER_OFFLINE		    = 15,
	E_CTI_TIMEOUT					    = 16,
	E_CTI_UNSPECIFIED_FAILURE		    = 17,
	E_CTI_INVALID_TIMEOUT			    = 18,
	E_CTI_INVALID_SERVICE_MASK		    = 19,
	E_CTI_INVALID_CALL_MSG_MASK		    = 20,
	E_CTI_INVALID_AGENT_STATE_MASK	    = 21,
	E_CTI_INVALID_RESERVED_FIELD	    = 22,
	E_CTI_INVALID_FIELD_LENGTH		    = 23,
	E_CTI_INVALID_DIGITS			    = 24,
	E_CTI_BAD_MESSAGE_FORMAT		    = 25,
	E_CTI_INVALID_TAG_FOR_MSG_TYPE	    = 26,
	E_CTI_INVALID_DEVICE_ID_TYPE	    = 27,
	E_CTI_INVALID_LCL_CONN_STATE	    = 28,
	E_CTI_INVALID_EVENT_CAUSE		    = 29,
	E_CTI_INVALID_NUM_PARTIES		    = 30,
	E_CTI_INVALID_SYS_EVENT_ID		    = 31,
	E_CTI_INCONSISTENT_AGENT_DATA	    = 32,
	E_CTI_INVALID_CONNECTION_ID_TYPE    = 33,
	E_CTI_INVALID_CALL_TYPE			    = 34,
	E_CTI_NOT_CALL_PARTY			    = 35,
	E_CTI_INVALID_PASSWORD			    = 36,
	E_CTI_CLIENT_DISCONNECTED		    = 37,

	LAST_STATUS_CODE_V2				    = E_CTI_CLIENT_DISCONNECTED,	/* version 2 ICM 2.0 */

	E_CTI_INVALID_OBJECT_STATE			= 38,
	E_CTI_INVALID_NUM_SKILL_GROUPS		= 39,
	E_CTI_INVALID_NUM_LINES				= 40,
	E_CTI_INVALID_LINE_TYPE				= 41,
	E_CTI_INVALID_ALLOCATION_STATE		= 42,
	E_CTI_INVALID_ANSWERING_MACHINE		= 43,
	E_CTI_INVALID_CALL_MANNER_TYPE		= 44,
	E_CTI_INVALID_CALL_PLACEMENT_TYPE	= 45,
	E_CTI_INVALID_CONSULT_TYPE			= 46,
	E_CTI_INVALID_FACILITY_TYPE			= 47,
	E_CTI_INVALID_MSG_TYPE_FOR_VERSION	= 48,
	E_CTI_INVALID_TAG_FOR_VERSION		= 49,
	E_CTI_INVALID_AGENT_WORK_MODE		= 50,

	LAST_STATUS_CODE_V3				    = E_CTI_INVALID_AGENT_WORK_MODE, /* CTI version 3, ICM 2.5 */

	E_CTI_INVALID_CALL_OPTION			= 51,
	E_CTI_INVALID_DESTINATION_COUNTRY	= 52,
	E_CTI_INVALID_ANSWER_DETECT_MODE	= 53,
	E_CTI_MUTUALLY_EXCLUS_DEVICEID_TYPES= 54,
	E_CTI_INVALID_MONITORID				= 55,
	E_CTI_SESSION_MONITOR_ALREADY_EXISTS= 56,
	E_CTI_SESSION_MONITOR_IS_CLIENTS	= 57,

	LAST_STATUS_CODE_V5				    = E_CTI_SESSION_MONITOR_IS_CLIENTS,

	E_CTI_INVALID_CALL_CONTROL_MASK				= 58,
	E_CTI_INVALID_FEATURE_MASK					= 59,
	E_CTI_INVALID_TRANSFER_CONFERENCE_SETUP_MASK= 60,
	E_CTI_INVALID_ARRAY_INDEX					= 61,
	E_CTI_INVALID_CHARACTER						= 62,
	E_CTI_CLIENT_NOT_FOUND						= 63,
	E_CTI_SUPERVISOR_NOT_FOUND					= 64,
	E_CTI_TEAM_NOT_FOUND						= 65,
	E_CTI_NO_CALL_ACTIVE						= 66,
	E_CTI_NAMED_VARIABLE_NOT_CONFIGURED			= 67,
	E_CTI_NAMED_ARRAY_NOT_CONFIGURED			= 68,
	E_CTI_INVALID_CALL_VARIABLE_MASK			= 69,
	E_CTI_ELEMENT_NOT_FOUND						= 70,
	E_CTI_INVALID_DISTRIBUTION_TYPE				= 71,
	E_CTI_INVALID_SKILL_GROUP					= 72,
	E_CTI_TOO_MUCH_DATA							= 73,
	E_CTI_VALUE_TOO_LONG						= 74,
	E_CTI_SCALAR_FUNCTION_ON_ARRAY				= 75,
	E_CTI_ARRAY_FUNCTION_ON_SCALAR				= 76,
	E_CTI_INVALID_NUM_NAMED_VARIABLES			= 77,
	E_CTI_INVALID_NUM_NAMED_ARRAYS				= 78,

	LAST_STATUS_CODE_V6				            = E_CTI_INVALID_NUM_NAMED_ARRAYS,

	E_CTI_INVALID_RTP_DIRECTION					= 79,
	E_CTI_INVALID_RTP_TYPE						= 80,

	LAST_STATUS_CODE_V7				            = E_CTI_INVALID_RTP_TYPE,

	E_CTI_CALLED_PARTY_DISPOSITION				= 81,
	E_CTI_INVALID_SUPERVISORY_ACTION			= 82,
	E_CTI_AGENT_TEAM_MONITOR_ALREADY_EXISTS		= 83,
	E_CTI_INVALID_SERVICE						= 84,
	E_CTI_SERVICE_CONFLICT						= 85,
	E_CTI_SKILL_GROUP_CONFLICT					= 86,
	E_CTI_INVALID_DEVICE						= 87,

	LAST_STATUS_CODE_V8			        	    = E_CTI_INVALID_DEVICE,

    E_CTI_RESERVED_88                           = 88,
    E_CTI_RESERVED_89                           = 89,
    E_CTI_RESERVED_90                           = 90,
    E_CTI_RESERVED_91                           = 91,

    E_CTI_SERVER_NOT_MASTER                     = 92,
    E_CTI_INVALID_CSQ                           = 93,
    E_CTI_JTAPI_CCM_PROBLEM                     = 94,
    E_CTI_RESERVED_95                           = 95,
    E_CTI_AUTO_CONFIG_RESET                     = 96,

	LAST_STATUS_CODE_V12		         	    = E_CTI_AUTO_CONFIG_RESET,

	LAST_STATUS_CODE				            = LAST_STATUS_CODE_V12
END_ENUM(CTILinkStatusCode)

//	CTILink Service Masks

BEGIN_ENUM(CTILinkServiceMask)
	CTI_SERVICE_DEBUG				= 0x80000000,
	CTI_SERVICE_CLIENT_EVENTS		= 0x00000001,
	CTI_SERVICE_CALL_DATA_UPDATE	= 0x00000002,
	CTI_SERVICE_CLIENT_CONTROL		= 0x00000004,
	CTI_SERVICE_CONNECTION_MONITOR	= 0x00000008,
	CTI_SERVICE_ALL_EVENTS			= 0x00000010,
	CTI_SERVICE_PERIPHERAL_MONITOR	= 0x00000020,	/* added in CTI version 5, ICM 3.0 */
	CTI_SERVICE_CLIENT_MONITOR		= 0x00000040,	/* added in CTI version 5, ICM 3.0 */
	CTI_SERVICE_SUPERVISOR			= 0x00000080,	/* added in CTI version 8, ICM 4.6 */
	CTI_SERVICE_SERVER			    = 0x00000100,	/* added in CTI version 8, ICM 4.6 */
    CTI_AGENT_STATE_CONTROL_ONLY	= 0x00002000,	/* added in CTI version 8, ICM 4.6 */
    CTI_SERVICE_CONFIG_EVENTS    	= 0x00040000,	/* added in CTI version 8, ICM 4.6 */

	CTI_SERVICE_UNUSED_V2			= 0x7fffffec,	/* version 2 ICM 2.0 */
	CTI_SERVICE_UNUSED_V3			= 0x7fffffe0,	/* version 3 ICM 2.5 */
	CTI_SERVICE_UNUSED_V5			= 0x7fffff80,	/* version 5 ICM 3.0 */
	CTI_SERVICE_UNUSED_V6			= 0x7fffff80,	/* version 6 ICM 4.1 */
	CTI_SERVICE_UNUSED_V7			= 0x7fffff80,	/* version 7 ICM 4.5 */
	CTI_SERVICE_UNUSED_V8			= 0x7ffffe00,	/* version 8 ICM 4.6 */

	CTI_SERVICE_UNUSED			= CTI_SERVICE_UNUSED_V8,
	CTI_SERVICE_ALL_MASK			= 0x000001ff	/* all but DEBUG */
END_ENUM(CTILinkServiceMask)

//	CTILink Call Event Message Masks

BEGIN_ENUM(CTILinkCallMsgMask)
	CALL_NULL_MASK					= 0x00000000,
	CALL_DELIVERED_MASK				= 0x00000001,
	CALL_QUEUED_MASK				= 0x00000002,
	CALL_ESTABLISHED_MASK			= 0x00000004,
	CALL_HELD_MASK					= 0x00000008,
	CALL_RETRIEVED_MASK				= 0x00000010,
	CALL_CLEARED_MASK				= 0x00000020,
	CALL_CONNECTION_CLEARED_MASK	= 0x00000040,
	CALL_ORIGINATED_MASK			= 0x00000080,
	CALL_CONFERENCED_MASK			= 0x00000100,
	CALL_TRANSFERRED_MASK			= 0x00000200,
	CALL_DIVERTED_MASK				= 0x00000400,
	CALL_SERVICE_INITIATED_MASK		= 0x00000800,
	CALL_TRANSLATION_ROUTE_MASK		= 0x00001000,
	BEGIN_CALL_MASK					= 0x00002000,
	END_CALL_MASK					= 0x00004000,
	CALL_DATA_UPDATE_MASK			= 0x00008000,
	CALL_FAILED_MASK				= 0x00010000,
    CALL_DEQUEUED_MASK              = 0x00040000,
    RTP_STARTED_MASK                = 0x00200000,
    RTP_STOPPED_MASK                = 0x00400000,

	CALL_ALL_MASK_V2				= 0x0001ffff,		/* version 2 ICM 2.0 */
	CALL_MASK_UNUSED_V2				= 0xfffe0000,		/* version 2 ICM 2.0 */

	CALL_ALL_MASK_V3				= 0x0001ffff,		/* version 3 ICM 2.5 */
	CALL_MASK_UNUSED_V3				= 0xfffe0000,		/* version 3 ICM 2.5 */

	CALL_REACHED_NETWORK_MASK		= 0x00020000,

	CALL_ALL_MASK_V5				= 0x0007ffff,		/* version 5 ICM 3.0 */
	CALL_MASK_UNUSED_V5				= 0xfff80000,		/* version 5 ICM 3.0 */

	AGENT_PRE_CALL_MASK				= 0x00080000,
	AGENT_PRE_CALL_ABORT_MASK		= 0x00100000,

	CALL_ALL_MASK_V6				= 0x001fffff,		/* version 6 ICM 4.1 */
	CALL_MASK_UNUSED_V6				= 0xffe00000,		/* version 6 ICM 4.1 */

	CALL_ALL_MASK_V7				= 0x007fffff,		/* version 7 ICM 4.5 */
	CALL_MASK_UNUSED_V7				= 0xff800000,		/* version 7 ICM 4.5 */
	
	AGENT_TEAM_CONFIG_MASK			= 0x00800000,

	CALL_ALL_MASK_V8				= 0x00ffffff,		/* version 8 ICM 4.6 */
	CALL_MASK_UNUSED_V8				= 0xff000000,		/* version 8 ICM 4.6 */

	CALL_ALL_MASK_V12				= 0x00ffffff,		/* version 12 ICM 7.0 */
	CALL_MASK_UNUSED_V12			= 0xff000000,		/* version 12 ICM 7.0 */
	
	CALL_ALL_MASK					= CALL_ALL_MASK_V12,
	CALL_MASK_UNUSED				= CALL_MASK_UNUSED_V12
END_ENUM(CTILinkCallMsgMask)

//	CTILink Agent State Masks

BEGIN_ENUM(CTILinkAgentStateMask)
	AGENT_NULL_MASK					= 0x00000000,
	AGENT_LOGIN_MASK				= 0x00000001,
	AGENT_LOGOUT_MASK				= 0x00000002,
	AGENT_NOT_READY_MASK			= 0x00000004,
	AGENT_AVAILABLE_MASK			= 0x00000008,
	AGENT_TALKING_MASK				= 0x00000010,
	AGENT_WORK_NOT_READY_MASK		= 0x00000020,
	AGENT_WORK_READY_MASK			= 0x00000040,
	AGENT_BUSY_OTHER_MASK			= 0x00000080,
	AGENT_RESERVED_MASK				= 0x00000100,
    AGENT_HOLD_MASK                 = 0x00000200,

	AGENT_ALL_MASK_V6				= 0x000001ff,		/* version 6 ICM 4.1 */
	AGENT_MASK_UNUSED_V6			= 0xfffffe00,		/* version 6 ICM 4.1 */

	AGENT_ALL_MASK_V7				= 0x000001ff,		/* version 7 ICM 4.5 */
	AGENT_MASK_UNUSED_V7			= 0xfffffe00,		/* version 7 ICM 4.5 */

	AGENT_ALL_MASK_V8				= 0x000001ff,		/* version 8 ICM 4.6 */
	AGENT_MASK_UNUSED_V8			= 0xfffffe00,		/* version 8 ICM 4.6 */

	AGENT_ALL_MASK_V12				= 0x000001ff,		/* version 12 ICM 7.0 */
	AGENT_MASK_UNUSED_V12			= 0xfffffe00,		/* version 12 ICM 7.0 */

	AGENT_ALL_MASK					= AGENT_ALL_MASK_V12,
	AGENT_MASK_UNUSED				= AGENT_MASK_UNUSED_V12
END_ENUM(CTILinkAgentStateMask)


//	CTILink Transfer Conference Setup Masks

BEGIN_ENUM(CTITransferConferenceSetupMask)
	CONF_SETUP_CONSULT_SPECIFIC					= 0x00000001,
	CONF_SETUP_CONSULT_ANY						= 0x00000002,
	CONF_SETUP_CONN_HELD						= 0x00000004,
	CONF_SETUP_ANY_TWO_CALLS					= 0x00000008,
	CONF_SETUP_SINGLE_ACD_CALL					= 0x00000010,
	TRANS_SETUP_SINGLE_ACD_CALL					= 0x00000020,
	CONF_SETUP_ANY_SINGLE_CALL					= 0x00000040,
	TRANS_SETUP_ANY_SINGLE_CALL					= 0x00000080,

	TRANSFERCONFERENCESETUP_ALL_MASK			= 0x000000ff,
	TRANSFERCONFERENCESETUP_MASK_UNUSED			= 0xffffff00
END_ENUM(CTITransferConferenceSetupMask)

//	CTILink Call Control Masks

BEGIN_ENUM(CTILinkCallControlMask)
	CONTROL_QUERY_AGENT_STATE				= 0x00000001,
	CONTROL_SET_AGENT_STATE					= 0x00000002,
	CONTROL_ALTERNATE_CALL					= 0x00000004,
	CONTROL_ANSWER_CALL						= 0x00000008,
	CONTROL_CLEAR_CALL						= 0x00000010,
	CONTROL_CLEAR_CONNECTION				= 0x00000020,
	CONTROL_CONFERENCE_CALL					= 0x00000040,
	CONTROL_CONSULTATION_CALL				= 0x00000080,
	CONTROL_DEFLECT_CALL					= 0x00000100,
	CONTROL_HOLD_CALL						= 0x00000200,
	CONTROL_MAKE_CALL						= 0x00000400,
	CONTROL_MAKE_PREDICTIVE_CALL			= 0x00000800,
	CONTROL_RECONNECT_CALL					= 0x00001000,
	CONTROL_RETRIEVE_CALL					= 0x00002000,
	CONTROL_TRANSFER_CALL					= 0x00004000,
	CONTROL_QUERY_DEVICE_INFO				= 0x00008000,
	CONTROL_SNAPSHOT_CALL					= 0x00010000,
	CONTROL_SNAPSHOT_DEVICE					= 0x00020000,
	CONTROL_SEND_DTMF_SIGNAL				= 0x00040000,

	CALLCONTROL_ALL_MASK					= 0x0007ffff,
	CALLCONTROL_MASK_UNUSED					= 0xfff80000
END_ENUM(CTILinkCallControlMask)

//	CTILink Other Feature Masks

BEGIN_ENUM(CTILinkFeatureMask)

	FEATURE_POST_ROUTE						= 0x00000001,
	FEATURE_UNIQUE_CONSULT_CALLID			= 0x00000002,

	FEATURE_ALL_MASK						= 0x00000003,
	FEATURE_MASK_UNUSED						= 0xfffffffc
END_ENUM(CTILinkFeatureMask)

//	CTILink Call Variable Masks

BEGIN_ENUM(CTILinkCallVariableMask)
	CALL_VAR_1_MASK				= 0x0001,
	CALL_VAR_2_MASK				= 0x0002,
	CALL_VAR_3_MASK				= 0x0004,
	CALL_VAR_4_MASK				= 0x0008,
	CALL_VAR_5_MASK				= 0x0010,
	CALL_VAR_6_MASK				= 0x0020,
	CALL_VAR_7_MASK				= 0x0040,
	CALL_VAR_8_MASK				= 0x0080,
	CALL_VAR_9_MASK				= 0x0100,
	CALL_VAR_10_MASK			= 0x0200,

	CALL_VAR_ALL_MASK			= 0x03ff,
	CALL_VAR_MASK_UNUSED		= 0xfc00
END_ENUM(CTILinkCallVariableMask)


//	CTILink Desk Settigs Masks

BEGIN_ENUM(CTIDeskSettingsMask)
	DESK_AVAIL_AFTER_INCOMING_MASK					= 0x00000001,
	DESK_AVAIL_AFTER_OUTGOING_MASK					= 0x00000002,		
	DESK_AUTO_ANSWER_ENABLED_MASK					= 0x00000004,		
	DESK_IDLE_REASON_REQUIRED_MASK					= 0x00000008,
	DESK_LOGOUT_REASON_REQUIRED_MASK				= 0x00000010,
	DESK_SUPERVISOR_CALLS_ALLOWED_MASK				= 0x00000020,
	DESK_AGENT_TO_AGENT_CALLS_ALLOWED				= 0x00000040,
	DESK_OUTBOUND_ACCESS_INTERNATIONAL_MASK			= 0x00000080,
	DESK_OUTBOUND_ACCESS_PUBLIC_NET_MASK			= 0x00000100,
	DESK_OUTBOUND_ACCESS_PRIVATE_NET_MASK			= 0x00000200,
	DESK_OUTBOUND_ACCESS_OPERATOR_ASSISTED_MASK		= 0x00000400,
	DESK_OUTBOUND_ACCESS_PBX_MASK					= 0x00000800,
	DESK_NON_ACD_CALLS_ALLOWED_MASK					= 0x00001000,
	DESK_AGENT_CAN_SELECT_GROUP_MASK				= 0x00002000,

	DESK_SETTINGS_ALL_MASK							= 0x00003fff,
	DESK_SETTINGS_ALL_MASK_UNUSED					= 0xfffc0000
END_ENUM(CTIDeskSettingsMask)

//	System Event codes

BEGIN_ENUM(CTILinkSystemEvent)
	SYS_CENTRAL_CONTROLLER_ONLINE	= 1,
	SYS_CENTRAL_CONTROLLER_OFFLINE	= 2,
	SYS_PERIPHERAL_ONLINE			= 3,	// PeripheralID in SystemEventArg1
	SYS_PERIPHERAL_OFFLINE			= 4,	// PeripheralID in SystemEventArg1
	SYS_TEXT_FYI					= 5,
	SYS_PERIPHERAL_GATEWAY_OFFLINE	= 6,
	SYS_CTI_SERVER_OFFLINE			= 7,
	SYS_CTI_SERVER_ONLINE			= 8,
	SYS_HALF_HOUR_CHANGE			= 9,
	SYS_INSTRUMENT_OUT_OF_SERVICE	= 10,
	SYS_INSTRUMENT_BACK_IN_SERVICE	= 11,

	LAST_SYSTEM_EVENT			= SYS_INSTRUMENT_BACK_IN_SERVICE
END_ENUM(CTILinkSystemEvent)



//	Floating field tag values

BEGIN_ENUM(CTILinkTag)
	INVALID_TAG					= 0,
	CLIENT_ID_TAG				= 1,
	CLIENT_PASSWORD_TAG			= 2,
	CLIENT_SIGNATURE_TAG		= 3,
	AGENT_EXTENSION_TAG			= 4,
	AGENT_ID_TAG				= 5,
	AGENT_INSTRUMENT_TAG		= 6,
	TEXT_TAG					= 7,
	ANI_TAG						= 8,
	UUI_TAG						= 9,
	DNIS_TAG					= 10,
	DIALED_NUMBER_TAG			= 11,
	CED_TAG						= 12,
	CALL_VARIABLE_1_TAG			= 13,
	CALL_VARIABLE_2_TAG			= 14,
	CALL_VARIABLE_3_TAG			= 15,
	CALL_VARIABLE_4_TAG			= 16,
	CALL_VARIABLE_5_TAG			= 17,
	CALL_VARIABLE_6_TAG			= 18,
	CALL_VARIABLE_7_TAG			= 19,
	CALL_VARIABLE_8_TAG			= 20,
	CALL_VARIABLE_9_TAG			= 21,
	CALL_VARIABLE_10_TAG		= 22,
	CTI_CLIENT_SIGNATURE_TAG	= 23,
	CTI_CLIENT_TIMESTAMP_TAG	= 24,
	CONNECTION_DEVID_TAG		= 25,
	ALERTING_DEVID_TAG			= 26,
	CALLING_DEVID_TAG			= 27,
	CALLED_DEVID_TAG			= 28,
	LAST_REDIRECT_DEVID_TAG		= 29,
	ANSWERING_DEVID_TAG			= 30,
	HOLDING_DEVID_TAG			= 31,
	RETREIVING_DEVID_TAG		= 32,
	RELEASING_DEVID_TAG			= 33,
	FAILING_DEVID_TAG			= 34,
	PRIMARY_DEVID_TAG			= 35,
	SECONDARY_DEVID_TAG			= 36,
	CONTROLLER_DEVID_TAG		= 37,
	ADDED_PARTY_DEVID_TAG		= 38,
	PARTY_CALLID_TAG			= 39,
	PARTY_DEVID_TYPE_TAG		= 40,
	PARTY_DEVID_TAG				= 41,
	TRANSFERRING_DEVID_TAG		= 42,
	TRANSFERRED_DEVID_TAG		= 43,
	DIVERTING_DEVID_TAG			= 44,
	QUEUE_DEVID_TAG				= 45,
	CALL_WRAPUP_DATA_TAG		= 46,
	NEW_CONNECTION_DEVID_TAG	= 47,

	LAST_TAG_V2					= NEW_CONNECTION_DEVID_TAG,	/* version 2 ICM 2.0 */

	TRUNK_USED_DEVID_TAG		= 48,
	AGENT_PASSWORD_TAG			= 49,
	ACTIVE_CONN_DEVID_TAG		= 50,
	FACILITY_CODE_TAG			= 51,
	OTHER_CONN_DEVID_TAG		= 52,
	HELD_CONN_DEVID_TAG			= 53,
	FORWARD_DEVID_TAG			= 54,
	LAST_NUMBER_DEVID_TAG		= 55,
	CALL_CONN_CALLID_TAG		= 56,
	CALL_CONN_DEVID_TYPE_TAG	= 57,
	CALL_CONN_DEVID_TAG			= 58,
	CALL_DEVID_TYPE_TAG			= 59,
	CALL_DEVID_TAG				= 60,
	CALL_DEV_CONN_STATE_TAG		= 61,
	SKILL_GROUP_NUMBER_TAG		= 62,
	SKILL_GROUP_ID_TAG			= 63,
	SKILL_GROUP_PRIORITY_TAG	= 64,
	SKILL_GROUP_STATE_TAG		= 65,
	OBJECT_NAME_TAG				= 66,
	DTMF_STRING_TAG				= 67,
	POSITION_ID_TAG				= 68,
	SUPERVISOR_ID_TAG			= 69,
	LINE_HANDLE_TAG				= 70,
	LINE_TYPE_TAG				= 71,
	ROUTER_CALL_KEY_DAY_TAG		= 72,
	ROUTER_CALL_KEY_CALLID_TAG	= 73,
	DATA_STRUCTURE_TAG			= 74,
	CALL_STATE_TAG				= 75,
	LAST_TAG_V3					= CALL_STATE_TAG, 	/* version 3 ICM 2.5 */


	MONITORED_DEVID_TAG			= 76,
	AUTHORIZATION_CODE_TAG		= 77,
	ACCOUNT_CODE_TAG			= 78,
	ORIGINATING_DEVICEID_TAG	= 79,
	ORIGINATING_LINEID_TAG		= 80,
	CLIENT_ADDRESS_TAG			= 81,

	LAST_TAG_V5					= CLIENT_ADDRESS_TAG, /* version 5 ICM 3.0  */

	
	NAMED_VARIABLE_TAG			= 82,
	NAMED_ARRAY_TAG				= 83,
	CALL_CONTROL_TABLE_TAG		= 84,

	LAST_TAG_V6					= CALL_CONTROL_TABLE_TAG, /* version 6 ICM 4.1 Enterprise Agent + Expanded Call Context*/


	LAST_TAG_V7					= CALL_CONTROL_TABLE_TAG, /* version 7 ICM 4.5 */

	SUPERVISOR_INSTRUMENT_TAG	= 85,
	ATC_AGENT_ID_TAG			= 86,
	AGENT_FLAGS_TAG				= 87,
	ATC_AGENT_STATE_TAG			= 88,
	ATC_STATE_DURATION_TAG		= 89,
	AGENT_CONNECTION_DEVID_TAG	= 90,
	SUPERVISOR_CONNECTION_DEVID_TAG	= 91,
	LIST_TEAM_ID_TAG				= 92,
	DEFAULT_DEVICE_PORT_ADDRESS_TAG	= 93,
	SERVICE_NAME_TAG				= 94,

	LAST_TAG_V8					= SERVICE_NAME_TAG, /* version 8 ICM 4.6 */

    CONFIG_MSG_MASK_TAG				= 95,

	LAST_TAG_V12					= CONFIG_MSG_MASK_TAG, /* version 12 ICM 7.0 */

	LAST_TAG					= LAST_TAG_V12
END_ENUM(CTILinkTag)


//	Agent State values
BEGIN_ENUM(CTILinkAgentState)
	CAGENT_STATE_LOGIN			= 0,
	CAGENT_STATE_LOGOUT			= 1,
    CAGENT_STATE_NOT_READY		= 2,
    CAGENT_STATE_READY		    = 3,
	CAGENT_STATE_TALKING		= 4,
	CAGENT_STATE_WORK_NOT_READY	= 5,
	CAGENT_STATE_WORK_READY		= 6,
	CAGENT_STATE_BUSY_OTHER		= 7,
	CAGENT_STATE_RESERVED		= 8,
	CAGENT_STATE_UNKNOWN		= 9,
	CAGENT_STATE_HOLD			= 10,

	CLAST_AGENT_STATE			= CAGENT_STATE_HOLD
END_ENUM(CTILinkAgentState)

//	Call Type values

BEGIN_ENUM(CTICallType)
	CALLTYPE_INVALID				= 0,
	CALLTYPE_ACD_IN					= 1,
	CALLTYPE_PREROUTE_ACD_IN		= 2,
	CALLTYPE_PREROUTE_DIRECT_AGENT	= 3,
	CALLTYPE_TRANSFER_IN			= 4,
	CALLTYPE_OVERFLOW_IN			= 5,
	CALLTYPE_OTHER_IN				= 6,
	CALLTYPE_AUTO_OUT				= 7,
	CALLTYPE_AGENT_OUT				= 8,
	CALLTYPE_OUT					= 9,
	CALLTYPE_AGENT_INSIDE			= 10,
	CALLTYPE_OFFERED				= 11,
	CALLTYPE_CONSULT				= 12,
	CALLTYPE_CONSULT_OFFERED		= 13,
	CALLTYPE_CONSULT_CONFERENCE		= 14,
	CALLTYPE_CONFERENCE				= 15,
	CALLTYPE_UNMONITORED			= 16,
	CALLTYPE_PREVIEW				= 17,
	CALLTYPE_RESERVATION			= 18,
	CALLTYPE_ASSIST					= 19,
	CALLTYPE_EMERGENCY				= 20,
	CALLTYPE_SUPERVISOR_MONITOR		= 21,
	CALLTYPE_SUPERVISOR_WHISPER		= 22,
	CALLTYPE_SUPERVISOR_BARGE_IN	= 23,
	CALLTYPE_SUPERVISOR_INTERCEPT	= 24,

	LAST_CALL_TYPE					= CALLTYPE_SUPERVISOR_INTERCEPT
END_ENUM(CTICallType)

//	Called Party Disposition values

BEGIN_ENUM(CALLEDPartyDisposition)
	CD_INVALID						= 0,
	CD_ABAND_NETWORK				= 1,
	CD_ABAND_LOCAL_QUEUE			= 2,
	CD_ABAND_RING					= 3,
	CD_ABAND_DELAY					= 4,
	CD_ABAND_INTERFLOW				= 5,
	CD_ABAND_AGENT_TERMINAL			= 6,
	CD_SHORT						= 7,
	CD_BUSY							= 8,
	CD_FORCED_BUSY					= 9,
	CD_DROP_NO_ANSWER				= 10,
	CD_DROP_BUSY					= 11,
	CD_DROP_REORDER					= 12,
	CD_DROP_HANDLED_PRIMARY_ROUTE	= 13,
	CD_DROP_HANDLED_OTHER			= 14,
	CD_REDIRECTED					= 15,
	CD_CUT_THROUGH					= 16,
	CD_INTRAFLOW					= 17,
	CD_INTERFLOW					= 18,
	CD_RING_NO_ANSWER				= 19,
	CD_INTERCEPT_REORDER			= 20,
	CD_INTERCEPT_DENIAL				= 21,
	CD_TIME_OUT						= 22,
	CD_VOICE_ENERGY					= 23,
	CD_NONCLASSIFIED_ENERGY_DETECT	= 24,
	CD_NO_CUT_THROUGH				= 25,
	CD_UABORT						= 26,
	CD_FAILED_SOFTWARE				= 27,
	CD_BLIND_TRANSFER				= 28,
	CD_ANNOUNCED_TRANSFER			= 29,
	CD_CONFERENCED					= 30,
	CD_DUPLICATE_TRANSFER			= 31,
	CD_UNMONITORED_DEVICE			= 32,
	CD_ANSWERING_MACHINE			= 33,

	LAST_CALLED_PARTY_DISPOSITION		= CD_ANSWERING_MACHINE
END_ENUM(CALLEDPartyDisposition)

BEGIN_ENUM(CTILineType)
	LINETYPE_INBOUND_ACD	= 0,
	LINETYPE_OUTBOUND_ACD	= 1,
	LINETYPE_INSIDE			= 2,
	LINETYPE_UNKNOWN		= 3,
	LINETYPE_SUPERVISOR		= 4,
	LINETYPE_MESSAGE		= 5,
	LINETYPE_HELP			= 6,
	LINETYPE_OUTBOUND		= 7,	// Outbound line (non-ACD)
	LINETYPE_DID			= 8,

	LAST_LINETYPE			= LINETYPE_DID
END_ENUM(CTILineType)

//	PG Status Masks

BEGIN_ENUM(CTILinkPGStatusMask)
	PGS_OK						= 0x00000000,
	PGS_OPC_DOWN				= 0x00000001,	// Peripheral Controller Down
	PGS_CC_DOWN					= 0x00000002,	// Central Controller DOwn
	PGS_PERIPHERAL_OFFLINE		= 0x00000004,
	PGS_CTI_SERVER_OFFLINE		= 0x00000008,	// (never reported by CTIServer itself, used by layered software)
	PGS_LIMITED_FUNCTION		= 0x00000010,	// (never reported by CTIServer itself, used by layered software)

	PGS_UNUSED					= 0xffffffe0
END_ENUM(CTILinkPGStatusMask)

//	Peripheral Type values

BEGIN_ENUM(CTILinkPeripheralType)
	PT_NONE					= 0xffff,
	PT_ASPECT				= 1,
	PT_MERIDIAN				= 2,
	PT_G2					= 3,
	PT_DEFINITY_ECS_NON_EAS	= 4,
	PT_DEFINITY_ECS_EAS		= 5,
	PT_GALAXY				= 6,
	PT_SPECTRUM				= 7,
	PT_VRU					= 8,
	PT_VRU_POLLED			= 9,
	PT_DMS100				= 10,
	PT_SIEMENS_9006			= 11,
	PT_SIEMENS_9005			= 12,
	PT_ALCATEL				= 13,
	PT_NEC_NEAX_2x00		= 14,
	PT_ACP_1000				= 15,
	PT_SYMPOSIUM			= 16,
	PT_ENTERPRISE_AGENT		= 17,
	PT_MD110				= 18,

	LAST_PERIPHERAL_TYPE	= PT_MD110
END_ENUM(CTILinkPeripheralType)

//	Local Connection State values

BEGIN_ENUM(CTILinkLclConnState)
	LCS_NONE			= 0xffff,
	LCS_NULL			= 0,
	LCS_INITIATE		= 1,
	LCS_ALERTING		= 2,
	LCS_CONNECT			= 3,
	LCS_HOLD			= 4,
	LCS_QUEUED			= 5,
	LCS_FAIL			= 6,

	LAST_LCL_CONN_STATE	= LCS_FAIL
END_ENUM(CTILinkLclConnState)

//	Call Event Cause values

BEGIN_ENUM(CTILinkCallEventCause)
	CEC_NONE					= 0xffff,
	CEC_ACTIVE_MONITOR			= 1,
	CEC_ALTERNATE				= 2,
	CEC_BUSY					= 3,
	CEC_CALL_BACK				= 4,
	CEC_CALL_CANCELLED			= 5,
	CEC_CALL_FORWARD_ALWAYS		= 6,
	CEC_CALL_FORWARD_BUSY		= 7,
	CEC_CALL_FORWARD_NO_ANSWER	= 8,
	CEC_CALL_FORWARD			= 9,
	CEC_CALL_NOT_ANSWERED		= 10,
	CEC_CALL_PICKUP				= 11,
	CEC_CAMP_ON					= 12,
	CEC_DEST_NOT_OBTAINABLE		= 13,
	CEC_DO_NOT_DISTURB			= 14,
	CEC_INCOMPATIBLE_DESTINATION= 15,
	CEC_INVALID_ACCOUNT_CODE	= 16,
	CEC_KEY_CONFERENCE			= 17,
	CEC_LOCKOUT					= 18,
	CEC_MAINTENANCE				= 19,
	CEC_NETWORK_CONGESTION		= 20,
	CEC_NETWORK_NOT_OBTAINABLE	= 21,
	CEC_NEW_CALL				= 22,
	CEC_NO_AVAILABLE_AGENTS		= 23,
	CEC_OVERRIDE				= 24,
	CEC_PARK					= 25,
	CEC_OVERFLOW				= 26,
	CEC_RECALL					= 27,
	CEC_REDIRECTED				= 28,
	CEC_REORDER_TONE			= 29,
	CEC_RESOURCES_NOT_AVAILABLE	= 30,
	CEC_SILENT_MONITOR			= 31,
	CEC_TRANSFER				= 32,
	CEC_TRUNKS_BUSY				= 33,
	CEC_VOICE_UNIT_INITIATOR	= 34,
	CEC_TIME_OUT				= 35,
	CEC_NEW_CALL_INTERFLOW		= 36,
	CEC_SIMULATION_INIT_REQUEST	= 37,
	CEC_SIMULATION_RESET_REQUEST= 38,
	CEC_CTI_LINK_DOWN			= 39,
	CEC_PERIPHERAL_RESET_REQUEST= 40,
	CEC_MD110_CONFERENCE_TRANSFER = 41,
	CEC_REMAINS_IN_Q			= 42,
	CEC_SUPERVISOR_ASSIST		= 43,
	CEC_EMERGENCY_CALL			= 44,
	CEC_SUPERVISOR_CLEAR		= 45,
	CEC_SUPERVISOR_MONITOR		= 46,
	CEC_SUPERVISOR_WHISPER		= 47,
	CEC_SUPERVISOR_BARGE_IN		= 48,
	CEC_SUPERVISOR_INTERCEPT	= 49,

	LAST_EVENT_CAUSE			= CEC_SUPERVISOR_INTERCEPT,

//	Extended Call Event Cause values for CALL_CLEARED

	CECX_BASE_VALUE						= 1000,

	CECX_ABAND_NETWORK					= CECX_BASE_VALUE+1,
	CECX_ABAND_LOCAL_QUEUE				= CECX_BASE_VALUE+2,
	CECX_ABAND_RING						= CECX_BASE_VALUE+3,
	CECX_ABAND_DELAY					= CECX_BASE_VALUE+4,
	CECX_ABAND_INTERFLOW				= CECX_BASE_VALUE+5,
	CECX_ABAND_AGENT_TERMINAL			= CECX_BASE_VALUE+6,
	CECX_SHORT							= CECX_BASE_VALUE+7,
	CECX_BUSY							= CECX_BASE_VALUE+8,
	CECX_FORCED_BUSY					= CECX_BASE_VALUE+9,
	CECX_DROP_NO_ANSWER					= CECX_BASE_VALUE+10,
	CECX_DROP_BUSY						= CECX_BASE_VALUE+11,
	CECX_DROP_REORDER					= CECX_BASE_VALUE+12,
	CECX_DROP_HANDLED_PRIMARY_ROUTE		= CECX_BASE_VALUE+13,
	CECX_DROP_HANDLED_OTHER				= CECX_BASE_VALUE+14,
	CECX_REDIRECTED						= CECX_BASE_VALUE+15,
	CECX_CUT_THROUGH					= CECX_BASE_VALUE+16,
	CECX_INTRAFLOW						= CECX_BASE_VALUE+17,
	CECX_INTERFLOW						= CECX_BASE_VALUE+18,
	CECX_RING_NO_ANSWER					= CECX_BASE_VALUE+19,
	CECX_INTERCEPT_REORDER				= CECX_BASE_VALUE+20,
	CECX_INTERCEPT_DENIAL				= CECX_BASE_VALUE+21,
	CECX_TIME_OUT						= CECX_BASE_VALUE+22,
	CECX_VOICE_ENERGY					= CECX_BASE_VALUE+23,
	CECX_NONCLASSIFIED_ENERGY_DETECT	= CECX_BASE_VALUE+24,
	CECX_NO_CUT_THROUGH					= CECX_BASE_VALUE+25,
	CECX_UABORT							= CECX_BASE_VALUE+26,
	CECX_FAILED_SOFTWARE				= CECX_BASE_VALUE+27,
	CECX_BLIND_TRANSFER					= CECX_BASE_VALUE+28,
	CECX_ANNOUNCED_TRANSFER				= CECX_BASE_VALUE+29,
	CECX_CONFERENCED					= CECX_BASE_VALUE+30,
	CECX_DUPLICATE_TRANSFER				= CECX_BASE_VALUE+31,
	CECX_UNMONITORED_DEVICE				= CECX_BASE_VALUE+32,
	CECX_ANSWERING_MACHINE				= CECX_BASE_VALUE+33,
	CECX_NETWORK_BLIND_TRANSFER			= CECX_BASE_VALUE+34,

	LAST_CECX_EVENT_CAUSE				= CECX_NETWORK_BLIND_TRANSFER
END_ENUM(CTILinkCallEventCause)

BEGIN_ENUM(CTICCXErrorCode)

    CCX_DEFAULT_ERROR_CODE              = 0,
    CCX_BASE_VALUE                      = 88000,
    CCX_JTAPI_CCM_PROBLEM               = CCX_BASE_VALUE + 1,
    CCX_LOOKUP_FAILURE                  = CCX_BASE_VALUE + 2,
    CCX_AGENT_DN_NOT_ASSIGNED           = CCX_BASE_VALUE + 3,
    CCX_AGENT_DEVICE_OFF                = CCX_BASE_VALUE + 4,
    CCX_AGENT_DEVICE_BUSY               = CCX_BASE_VALUE + 5,
    CCX_RMCM_CONTACT_NULL               = CCX_BASE_VALUE + 6,
    CCX_RMCM_CONTACT_INVALID            = CCX_BASE_VALUE + 7,
    CCX_AGENT_NULL                      = CCX_BASE_VALUE + 8,
    CCX_AGENT_INVALID                   = CCX_BASE_VALUE + 9,
    CCX_INVALID_ARGUMENT                = CCX_BASE_VALUE + 10,
    CCX_NO_CALLBACK_FROM_AGENT          = CCX_BASE_VALUE + 11,
    CCX_CALL_ID_NULL                    = CCX_BASE_VALUE + 12,
    CCX_CALL_OBJECT_NULL                = CCX_BASE_VALUE + 13,
    CCX_JTAPI_PROVIDER_NULL             = CCX_BASE_VALUE + 14,
    CCX_DIALED_NUMBER_NULL              = CCX_BASE_VALUE + 15,
    CCX_DEVICE_ID_NULL                  = CCX_BASE_VALUE + 16,
    CCX_TERMINAL_CONNECTION_NULL        = CCX_BASE_VALUE + 17,
    CCX_CALL_CONTROL_MASK_NOT_ON        = CCX_BASE_VALUE + 18,
    CCX_AGENT_QUEUE_STATUS              = CCX_BASE_VALUE + 19,
    CCX_ICD_RTDM_NULL                   = CCX_BASE_VALUE + 20,
    CCX_CSQ_ICD_STATUS                  = CCX_BASE_VALUE + 21,
    CCX_OVERALL_ICD_STATUS              = CCX_BASE_VALUE + 22,
    CCX_INVALID_SUPERVISORY_ACTION      = CCX_BASE_VALUE + 23,
    CCX_CALL_DATA_UPDATE_MASK_NOT_ON    = CCX_BASE_VALUE + 24,
    CCX_OVERALL_LIMIT_EXCEEDED          = CCX_BASE_VALUE + 25,
    CCX_CALL_ID_INVALID                 = CCX_BASE_VALUE + 26,
    CCX_SUPERVISOR_UNAVAILABLE          = CCX_BASE_VALUE + 27,
    CCX_UNSUPPORTED_OPERATION           = CCX_BASE_VALUE + 28,
    CCX_CALL_ID_NOT_IN_PROVIDER         = CCX_BASE_VALUE + 29,
    CCX_DEVICE_RESTRICTED               = CCX_BASE_VALUE + 30,
    CCX_LINE_RESTRICTED                 = CCX_BASE_VALUE + 31,
    CCX_AGENT_LINE_ON_MULTIPLE_DEVICES  = CCX_BASE_VALUE + 32,
    CCX_USER_OPERATION_FAILED           = CCX_BASE_VALUE + 33,
    CCX_PROVIDER_OPERATION_FAILED       = CCX_BASE_VALUE + 34,
    CCX_PASSWORD_LOCKED                 = CCX_BASE_VALUE + 35,
    CCX_PASSWORD_EXPIRED                = CCX_BASE_VALUE + 36,
    CCX_PASSWORD_EXPIRED_SUCCESS        = CCX_BASE_VALUE + 37,
    CCX_PASSWORD_HACKED_LOCKED          = CCX_BASE_VALUE + 38,
    CCX_PASSWORD_INACTIVE_LOCKED        = CCX_BASE_VALUE + 39,
    CCX_PASSWORD_MUST_CHANGE            = CCX_BASE_VALUE + 40,

    LAST_CCX_ERROR_CODE 				= CCX_PASSWORD_MUST_CHANGE
END_ENUM(CTIUccxErrorCode)


BEGIN_ENUM(CTILinkConnectionDeviceIDType)
	CONNECTION_ID_NONE				= 0xffff,
	CONNECTION_ID_STATIC			= 0,
	CONNECTION_ID_DYNAMIC			= 1,

	LAST_CONNECTION_ID_TYPE				= CONNECTION_ID_DYNAMIC
END_ENUM(CTILinkConnectionDeviceIDType)

BEGIN_ENUM(CTILinkDeviceIDType)
	DEVID_NONE						= 0xffff,
    DEVID_DEVICE_IDENTIFIER         = 0,
	DEVID_TRUNK_IDENTIFIER			= 70,
	DEVID_TRUNK_GROUP_IDENTIFIER	= 71,
    DEVID_CTI_PORT                  = 73,
    DEVID_ROUTE_POINT               = 74,
    DEVID_AGENT_DEVICE              = 76,
    DEVID_QUEUE                     = 77,

	LAST_DEVICE_ID_TYPE				= DEVID_QUEUE
END_ENUM(CTILinkDeviceIDType)

BEGIN_ENUM(CTIObjectState)
	OBJECT_STATE_NORMAL				= 0,
	OBJECT_STATE_WARNING			= 1,
	OBJECT_STATE_ERROR				= 2,

	LAST_OBJECT_STATE				= OBJECT_STATE_ERROR
END_ENUM(CTIObjectState)

//	Control Failure Codes

BEGIN_ENUM(CTIControlFailureCode)
    CF_GENERIC_UNSPECIFIED						= 0,
    CF_GENERIC_OPERATION						= 1,
    CF_REQUEST_INCOMPATIBLE_WITH_OBJECT			= 2,
    CF_VALUE_OUT_OF_RANGE						= 3,
    CF_OBJECT_NOT_KNOWN							= 4,
    CF_INVALID_CALLING_DEVICE					= 5,
    CF_INVALID_CALLED_DEVICE					= 6,
    CF_INVALID_FORWARDING_DESTINATION			= 7,
    CF_PRIVILEGE_VIOLATION_ON_SPECIFIED_DEVICE	= 8,
    CF_PRIVILEGE_VIOLATION_ON_CALLED_DEVICE		= 9,
    CF_PRIVILEGE_VIOLATION_ON_CALLING_DEVICE	= 10,
    CF_INVALID_CSTA_CALL_IDENTIFIER				= 11,
    CF_INVALID_CSTA_DEVICE_IDENTIFIER			= 12,
    CF_INVALID_CSTA_CONNECTION_IDENTIFIER		= 13,
    CF_INVALID_DESTINATION						= 14,
    CF_INVALID_FEATURE							= 15,
    CF_INVALID_ALLOCATION_STATE					= 16,
    CF_INVALID_CROSS_REF_ID						= 17,
    CF_INVALID_OBJECT_TYPE						= 18,
    CF_SECURITY_VIOLATION						= 19,

    CF_GENERIC_STATE_INCOMPATIBILITY			= 21,
    CF_INVALID_OBJECT_STATE						= 22,
    CF_INVALID_CONNECTION_ID_FOR_ACTIVE_CALL	= 23,
    CF_NO_ACTIVE_CALL							= 24,
    CF_NO_HELD_CALL								= 25,
    CF_NO_CALL_TO_CLEAR							= 26,
    CF_NO_CONNECTION_TO_CLEAR					= 27,
    CF_NO_CALL_TO_ANSWER						= 28,
    CF_NO_CALL_TO_COMPLETE						= 29,

    CF_GENERIC_SYSTEM_RESOURCE_AVAILABILITY		= 31,
    CF_SERVICE_BUSY								= 32,
    CF_RESOURCE_BUSY							= 33,
    CF_RESOURCE_OUT_OF_SERVICE					= 34,
    CF_NETWORK_BUSY								= 35,
    CF_NETWORK_OUT_OF_SERVICE					= 36,
    CF_OVERALL_MONITOR_LIMIT_EXCEEDED			= 37,
    CF_CONFERENCE_MEMBER_LIMIT_EXCEEDED			= 38,

    CF_GENERIC_SUBSCRIBED_RESOURCE_AVAILABILITY	= 41,
    CF_OBJECT_MONITOR_LIMIT_EXCEEDED			= 42,
    CF_EXTERNAL_TRUNK_LIMIT_EXCEEDED			= 43,
    CF_OUTSTANDING_REQUEST_LIMIT_EXCEEDED		= 44,

    CF_GENERIC_PERFORMANCE_MANAGEMENT			= 51,
    CF_PERFORMANCE_LIMIT_EXCEEDED				= 52,

    CF_SEQUENCE_NUMBER_VIOLATED					= 61,
    CF_TIME_STAMP_VIOLATED						= 62,
    CF_PAC_VIOLATED								= 63,
    CF_SEAL_VIOLATED							= 64,

    CF_GENERIC_UNSPECIFIED_REJECTION			= 70,
    CF_GENERIC_OPERATION_REJECTION				= 71,
    CF_DUPLICATE_INVOCATION_REJECTION			= 72,
    CF_UNRECOGNIZED_OPERATION_REJECTION			= 73,
    CF_MISTYPED_ARGUMENT_REJECTION				= 74,
    CF_RESOURCE_LIMITATION_REJECTION			= 75,
    CF_ACS_HANDLE_TERMINATION_REJECTION			= 76,
    CF_SERVICE_TERMINATION_REJECTION			= 77,
    CF_REQUEST_TIMEOUT_REJECTION				= 78,
    CF_REQUESTS_ON_DEVICE_EXCEEDED_REJECTION	= 79,

	LAST_LOW_CONTROL_FAILURE_CODE = CF_REQUESTS_ON_DEVICE_EXCEEDED_REJECTION,

	//

	FIRST_MID_CONTROL_FAILURE_CODE = 256,

	CF_INVALID_AGENT_ID_SPECIFIED				= 256,
	CF_INVALID_PASSWORD_SPECIFIED				= 257,
	CF_INVALID_AGENT_ID_OR_PASSWORD_SPECIFIED	= 258,
	CF_SPECIFIED_AGENT_ALREADY_SIGNED_ON		= 259,
	CF_INVALID_LOGON_DEVICE_SPECIFIED			= 260,
	CF_INVALID_ANSWERING_DEVICE_SPECIFIED		= 261,
	CF_INVALID_SKILL_GROUP_SPECIFIED			= 262,
	CF_INVALID_CLASS_OF_SERVICE_SPECIFIED		= 263,
	CF_INVALID_TEAM_SPECIFIED					= 264,
	CF_INVALID_AGENT_WORKMODE					= 265,
	CF_INVALID_AGENT_REASON_CODE				= 266,
	CF_ADJUNCT_SWITCH_COMM_ERROR				= 267,
	CF_AGENT_NOT_PARTY_ON_CALL					= 268,
	CF_INTERNAL_PROCESSING_ERROR				= 269,
	CF_TAKE_CALL_CONTROL_REJECTION				= 270,
	CF_TAKE_DOMAIN_CONTROL_REJECTION			= 271,
	CF_REQUESTED_SERVICE_NOT_REGISTERED			= 272,
	CF_INVALID_CONSULT_TYPE						= 273,
	CF_ANSMAP_OR_ADPARAM_FIELD_NOT_VALID		= 274,
	CF_INVALID_CALL_CONTROL_TABLE_SPECIFIED		= 275,
	CF_INVALID_DIGITS_RNATIMEOUT_AMSDELAY_OR_COUNTRY = 276,
	CF_ANSWER_DETECT_PORT_UNAVAILABLE			= 277,
	CF_VIRTUAL_AGENT_UNAVAILABLE				= 278,
	CF_TAKEBACK_N_XFER_ROUTE_END				= 279,
	CF_WRAPUP_DATA_REQUIRED						= 280,
	CF_REASON_CODE_REQUIRED						= 281,

	LAST_MID_CONTROL_FAILURE_CODE = CF_REASON_CODE_REQUIRED,

	//

	FIRST_HI_CONTROL_FAILURE_CODE = 1001,

	CF_UNKNOWN_INTERFACE_CTRLR_ID				= 1001,
	CF_INVALID_INTERFACE_CTRLR_TYPE				= 1002,
	CF_SOFTWARE_REV_NO_SUPPORTED				= 1003,
	CF_UNKNOWN_PID								= 1004,
	CF_INVALID_TABLE_SPECIFIED					= 1005,
	CF_PD_SERVICE_INACTIVE						= 1006,
	CF_UNKNOWN_ROUTING_CLIENT_ID				= 1007,
	CF_RC_SERVICE_INACTIVATE					= 1008,
	CF_INVALID_DIALED_NUMBER					= 1009,
	CF_INVALID_PARAMETER						= 1010,
	CF_UNKNOWN_ROUTING_PROBLEM					= 1011,
	CF_UNSUPPORTED_PD_MESSAGE_REVISION			= 1012,
	CF_UNSUPPORTED_RC_MESSAGE_REVISION			= 1013,
	CF_UNSUPPORTED_IC_MESSAGE_REVISION			= 1014,
	CF_RC_SERVICE_INACTIVATE_PIM				= 1015,

	LAST_HI_CONTROL_FAILURE_CODE = CF_RC_SERVICE_INACTIVATE_PIM
END_ENUM(CTIControlFailureCode)

BEGIN_ENUM(CTIAllocationState)
	ALLOC_CALL_DELIVERED			= 0,
	ALLOC_CALL_ESTABLISHED			= 1,

	LAST_ALLOCATION_STATE			= ALLOC_CALL_ESTABLISHED
END_ENUM(CTIAllocationState)

BEGIN_ENUM(CTIForwardType)
	FWT_IMMEDIATE					= 0,
	FWT_BUSY						= 1,
	FWT_NO_ANS						= 2,
	FWT_BUSY_INT					= 3,
	FWT_BUSY_EXT					= 4,
	FWT_NO_ANS_INT					= 5,
	FWT_NO_ANS_EXT					= 6,

	LAST_FORWARD_TYPE				= FWT_NO_ANS_EXT
END_ENUM(CTIForwardType)

BEGIN_ENUM(CTIDeviceType)
	DEVT_STATION					= 0,
	DEVT_LINE						= 1,
	DEVT_BUTTON						= 2,
	DEVT_ACD						= 3,
	DEVT_TRUNK						= 4,
	DEVT_OPERATOR					= 5,

	DEVT_STATION_GROUP				= 16,
	DEVT_LINE_GROUP					= 17,
	DEVT_BUTTON_GROUP				= 18,
	DEVT_ACD_GROUP					= 19,
	DEVT_TRUNK_GROUP				= 20,
	DEVT_OPERATOR_GROUP				= 21,

	DEVT_OTHER						= 255
END_ENUM(CTIDeviceType)

BEGIN_ENUM(CTIDeviceClass)
	DEVC_OTHER						= 0x10,
	DEVC_IMAGE						= 0x20,
	DEVC_DATA						= 0x40,
	DEVC_VOICE						= 0x80
END_ENUM(CTIDeviceClass)

BEGIN_ENUM(CTICallOption)
	COPT_UNSPECIFIED				= 0,
	COPT_CALLING_AGENT_ONLINE		= 1,
	COPT_CALLING_AGENT_RESERVED		= 2,
	COPT_CALLING_AGENT_NOT_RESERVED	= 3,
	COPT_CALLING_AGENT_BUZZ_BASE	= 4,
	COPT_CALLING_AGENT_BEEP_HSET	= 5,
	COPT_SERVICE_CIRCUIT_ON			= 6,

	LAST_CALL_OPTION				= COPT_SERVICE_CIRCUIT_ON
END_ENUM(CTICallOption)

BEGIN_ENUM(CTICallPlacementType)
	CPT_UNSPECIFIED					= 0,
	CPT_LINE_CALL					= 1,
	CPT_OUTBOUND					= 2,
	CPT_OUTBOUND_NO_ACCESS_CODE		= 3,
	CPT_DIRECT_POSITION				= 4,
	CPT_DIRECT_AGENT				= 5,
	CPT_SUPERVISOR_ASSIST			= 6,

	LAST_CALL_PLACEMENT_TYPE		= CPT_SUPERVISOR_ASSIST
END_ENUM(CTICallPlacementType)

BEGIN_ENUM(CTICallMannerType)
	CMT_UNSPECIFIED					= 0,
	CMT_POLITE						= 1,
	CMT_BELLIGERENT					= 2,
	CMT_SEMI_POLITE					= 3,
	CMT_RESERVED					= 4,

	LAST_CALL_MANNER_TYPE			= CMT_RESERVED
END_ENUM(CTICallMannerType)

BEGIN_ENUM(CTIConsultType)
	CT_UNSPECIFIED					= 0,
	CT_TRANSFER						= 1,
	CT_CONFERENCE					= 2,

	LAST_CONSULT_TYPE				= CT_CONFERENCE
END_ENUM(CTIConsultType)

BEGIN_ENUM(CTIFacilityType)
	FT_UNSPECIFIED					= 0,
	FT_TRUNK_GROUP					= 1,
	FT_SKILL_GROUP					= 2,

	LAST_FACILITY_TYPE				= FT_SKILL_GROUP
END_ENUM(CTIFacilityType)

BEGIN_ENUM(CTIAnsMachine)
	AM_UNSPECIFIED					= 0,
	AM_CONNECT						= 1,
	AM_DISCONNECT					= 2,
	AM_NONE							= 3,
	AM_NONE_NO_MODEM				= 4,
	AM_CONNECT_NO_MODEM				= 5,

	LAST_ANS_MACHINE				= AM_CONNECT_NO_MODEM
END_ENUM(CTIAnsMachine)

BEGIN_ENUM(CTIAgentWorkMode)
	AWM_UNSPECIFIED					= 0,
	AWM_AUTO_IN						= 1,
	AWM_MANUAL_IN					= 2,

	LAST_AGENT_WORK_MODE			= AWM_MANUAL_IN
END_ENUM(CTIAgentWorkMode)

BEGIN_ENUM(CTIQueryDeviceDataType)
	QDDT_NONE						= 0,
	QDDT_LINE_DEV_CAPS				= 1,
	QDDT_LINE_ADDR_CAPS				= 2,
	QDDT_LINE_AGENT_CAPS			= 3,

	LAST_QUERY_DEVICE_DATA_TYPE		= QDDT_LINE_AGENT_CAPS
END_ENUM(CTIQueryDeviceDataType)

BEGIN_ENUM(CTIAnswerDetectMode)
	ADM_UNSPECIFIED					= 0,
	ADM_VOICE_THRESHOLD				= 1,
	ADM_VOICE_END					= 2,
	ADM_VOICE_END_DELAY				= 3,
	ADM_VOICE_AND_BEEP				= 4,
	ADM_BEEP						= 5,

	LAST_ANSWER_DETECT_MODE		= ADM_BEEP
END_ENUM(CTIAnswerDetectMode)


BEGIN_ENUM(CTIDestinationCountry)
	DEST_UNSPECIFIED				= 0,
	DEST_US_AND_CANADA				= 1,

	LAST_DESTINATION_COUNTRY		= DEST_US_AND_CANADA
END_ENUM(CTIDestinationCountry)

BEGIN_ENUM(CTIDistributionType)
	DISTRIBUTE_TO_CLIENT			= 0,
	DISTRIBUTE_TO_SUPERVISOR		= 1,
	DISTRIBUTE_TO_TEAM				= 2,
	DISTRIBUTE_TO_ALL				= 3,

	LAST_DISTRIBUTION_TYPE			= DISTRIBUTE_TO_ALL
END_ENUM(CTIDistributionType)

BEGIN_ENUM(CTIRTPDirection)
	RTP_INPUT						= 0,
	RTP_OUTPUT						= 1,
	RTP_BI_DIRECTIONAL				= 2,

	LAST_RTP_DIRECTION				= RTP_BI_DIRECTIONAL
END_ENUM(CTIRTPDirection)

BEGIN_ENUM(CTIRTPType)
	RTP_TYPE_AUDIO					= 0,
	RTP_TYPE_VIDEO					= 1,
	RTP_TYPE_DATA					= 2,

	LAST_RTP_TYPE					= RTP_TYPE_DATA
END_ENUM(CTIRTPType)

BEGIN_ENUM(CTISupervisoryAction)
	SA_SUPERVISOR_CLEAR				= 0,
	SA_SUPERVISOR_MONITOR			= 1,
	SA_SUPERVISOR_WHISPER			= 2,
	SA_SUPERVISOR_BARGE_IN			= 3,
	SA_SUPERVISOR_INTERCEPT			= 4,

	LAST_SUPERVISORY_ACTION			= SA_SUPERVISOR_INTERCEPT
END_ENUM(CTISupervisoryAction)

BEGIN_ENUM(CTIAgentFlag)
	ATC_REGULAR_AGENT				= 0,
	ATC_PRIMARY_SUPERVISOR			= 1,
	ATC_TEMPORARY_AGENT				= 2,
	ATC_SUPERVISOR					= 3,

	LAST_AGENT_FLAG			= ATC_SUPERVISOR
END_ENUM(CTIAgentFlag)

BEGIN_ENUM(CTIServerMode)
	CTI_SERVER_EXCLUSIVE			= 0,
	CTI_SERVER_ROUND_ROBIN			= 1,
	CTI_SERVER_PARALLEL				= 2,

	LAST_SERVER_MODE				= CTI_SERVER_PARALLEL
END_ENUM(CTIServerMode)
//
//	Definitions of CTILink data types
//

typedef	char				CTI_CHAR;
typedef	unsigned char		CTI_UCHAR;
typedef	short				CTI_SHORT;
typedef	unsigned short		CTI_USHORT;
typedef	long				CTI_INT;
typedef	unsigned long		CTI_UINT;
typedef	short				CTI_BOOL;
typedef struct CTILinkMsgHdr {
	CTI_UINT				MessageLength;			// Not including header
	CTI_UINT				MessageType;
} CTI_MHDR;

typedef struct CTINamedVariable {
	CTI_UCHAR				Tag;
	CTI_UCHAR				FieldLength;		
	CTI_CHAR				VariableName[MAX_VAR_NAME_LENGTH];
	CTI_CHAR				VariableValue[MAX_VAR_VALUE_LENGTH];
} CTI_NAMEDVAR;

typedef struct CTINamedArray {
	CTI_UCHAR				Tag;
	CTI_UCHAR				FieldLength;
	CTI_UCHAR				VariableIndex;
	CTI_CHAR				VariableName[MAX_VAR_NAME_LENGTH];
	CTI_CHAR				VariableValue[MAX_VAR_VALUE_LENGTH];
} CTI_NAMEDARRAY;

#endif


